//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Note.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int IDNote { get; set; }
        public string Title { get; set; }
        public string TextNote { get; set; }
        public int IDAuthor { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
